databases:
  - name: bookmark_list_production
    databaseName: bookmark_list_production
    user: bookmark_list
    region: singapore

services:
  - type: web
    name: bookmark_list_production
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookmark_list_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false